# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    if not('mpi' in bld.env['MODULES_NOT_BUILT']):
        # Example only works with two ranks; MPI must be present
        obj = bld.create_ns3_program('simple-distributed-channel-two-ranks', 
                                     ['simple-distributed', 'point-to-point', 'internet', 'nix-vector-routing', 'applications'])
        obj.source = 'simple-distributed-channel-two-ranks.cc'
    
    obj = bld.create_ns3_program('simple-distributed-channel-scaling', 
                                 ['simple-distributed', 'point-to-point', 'internet', 'nix-vector-routing', 'applications'])
    obj.source = 'simple-distributed-channel-scaling.cc'

