# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('multicast-flow-monitor', ['internet', 'config-store', 'stats'])
    module.source = [
       'model/multicast-flow-monitor.cc',
       'model/multicast-flow-classifier.cc',
       'model/multicast-flow-probe.cc',
       'model/ipv4-multicast-flow-classifier.cc',
       'model/ipv4-multicast-flow-probe.cc'
        ]
    module.source.append("helper/multicast-flow-monitor-helper.cc")

    module_test = bld.create_ns3_module_test_library('multicast-flow-monitor')
    module_test.source = [ ]

    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #   'test/flow-monitor-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'multicast-flow-monitor'
    headers.source = [
       'model/multicast-flow-monitor.h',
       'model/multicast-flow-probe.h',
       'model/multicast-flow-classifier.h',
       'model/ipv4-multicast-flow-classifier.h',
       'model/ipv4-multicast-flow-probe.h']
    headers.source.append("helper/multicast-flow-monitor-helper.h")

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

