# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('multicast-flow-monitor-example', ['multicast-flow-monitor', 'internet', 'wifi', 'applications', 'mobility'])
    obj.source = 'multicast-flow-monitor-example.cc'

